FROM nginx:alpine

LABEL maintainer="Aomd <g00665@163.com>"

COPY nginx.conf /etc/nginx/

RUN set -x ; \
    addgroup -g 82 -S www-data ; \
    adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

EXPOSE 80 81 443